/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import forme.clan.FSelektovanjeClana;
import domen.Administrator;
import domen.Clan;
import domen.TipKorisnika;
import forme.clan.FClan;
import forme.usluga.FSelektovanjeUsluge;
import forme.usluga.FUsluga;
import forme.zahtev.FOdgovorNaZahteve;
import forme.zahtev.FPrikazZahteva;
import forme.zahtev.FZahtev;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import niti.NitSat;

/**
 *
 * @author USER
 */
public class FGlavna extends javax.swing.JFrame {

    private TipKorisnika tip;

    public FGlavna(TipKorisnika tip) {
        initComponents();
        podesiFormu(tip);

    }

    private void podesiFormu(TipKorisnika tip1) {
        setTip(tip1);
        postaviKorisnika();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        prilagodiFormu();
        pokreniNitSat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCurrentUser = new javax.swing.JTextField();
        lblSat = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmClan = new javax.swing.JMenu();
        jmiNoviClan = new javax.swing.JMenuItem();
        jmiPretragaClanova = new javax.swing.JMenuItem();
        jmUsluga = new javax.swing.JMenu();
        jmiNovaUsluga = new javax.swing.JMenuItem();
        jmiPretragaUsluga = new javax.swing.JMenuItem();
        jmZahtev = new javax.swing.JMenu();
        jmiPodnesiZahtev = new javax.swing.JMenuItem();
        jmiOdgovoriNaZahteve = new javax.swing.JMenuItem();
        jmiMojiZahtevi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Trenutni korisnik:");

        txtCurrentUser.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jmClan.setText("Clan");

        jmiNoviClan.setText("Kreiraj clana");
        jmiNoviClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNoviClanActionPerformed(evt);
            }
        });
        jmClan.add(jmiNoviClan);

        jmiPretragaClanova.setText("Pretraga clanova");
        jmiPretragaClanova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaClanovaActionPerformed(evt);
            }
        });
        jmClan.add(jmiPretragaClanova);

        jMenuBar1.add(jmClan);

        jmUsluga.setText("Usluga");

        jmiNovaUsluga.setText("Kreiraj uslugu");
        jmiNovaUsluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNovaUslugaActionPerformed(evt);
            }
        });
        jmUsluga.add(jmiNovaUsluga);

        jmiPretragaUsluga.setText("Pretraga usluga");
        jmiPretragaUsluga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaUslugaActionPerformed(evt);
            }
        });
        jmUsluga.add(jmiPretragaUsluga);

        jMenuBar1.add(jmUsluga);

        jmZahtev.setText("Zahtev");

        jmiPodnesiZahtev.setText("Podnesi zahtev");
        jmiPodnesiZahtev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPodnesiZahtevActionPerformed(evt);
            }
        });
        jmZahtev.add(jmiPodnesiZahtev);

        jmiOdgovoriNaZahteve.setText("Odgovori na zahteve");
        jmiOdgovoriNaZahteve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOdgovoriNaZahteveActionPerformed(evt);
            }
        });
        jmZahtev.add(jmiOdgovoriNaZahteve);

        jmiMojiZahtevi.setText("Moji zahtevi");
        jmiMojiZahtevi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMojiZahteviActionPerformed(evt);
            }
        });
        jmZahtev.add(jmiMojiZahtevi);

        jMenuBar1.add(jmZahtev);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSat, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSat, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNoviClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNoviClanActionPerformed
        JDialog formaNoviClan = new FClan(this, true, FormMode.NEW);
        formaNoviClan.setVisible(true);
    }//GEN-LAST:event_jmiNoviClanActionPerformed

    private void jmiPretragaClanovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaClanovaActionPerformed
        JDialog formaPretraga = new FSelektovanjeClana(this, true);
        formaPretraga.setVisible(true);
    }//GEN-LAST:event_jmiPretragaClanovaActionPerformed

    private void jmiNovaUslugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNovaUslugaActionPerformed
        new FUsluga(this, true, FormMode.NEW).setVisible(true);
    }//GEN-LAST:event_jmiNovaUslugaActionPerformed

    private void jmiPretragaUslugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaUslugaActionPerformed
        new FSelektovanjeUsluge(this, true).setVisible(true);
    }//GEN-LAST:event_jmiPretragaUslugaActionPerformed

    private void jmiPodnesiZahtevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPodnesiZahtevActionPerformed
        new FZahtev(this, true, FormMode.NEW).setVisible(true);
    }//GEN-LAST:event_jmiPodnesiZahtevActionPerformed

    private void jmiOdgovoriNaZahteveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOdgovoriNaZahteveActionPerformed
        new FOdgovorNaZahteve(this, true).setVisible(true);
    }//GEN-LAST:event_jmiOdgovoriNaZahteveActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        String poruka = Kontroler.getInstance().zavrsiSaRadom();
        JOptionPane.showMessageDialog(this, poruka, "Kraj rada", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_formWindowClosing

    private void jmiMojiZahteviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMojiZahteviActionPerformed
        new FPrikazZahteva(this, true).setVisible(true);
    }//GEN-LAST:event_jmiMojiZahteviActionPerformed

    /**
     * @param args the command line arguments
     */
    private void postaviKorisnika() {
        if (tip == TipKorisnika.CLAN) {
            Clan c = (Clan) Kontroler.getInstance().getMapa().get("clan");
            txtCurrentUser.setText(c.toString());
        }else{
            Administrator a = (Administrator) Kontroler.getInstance().getMapa().get("admin");
            txtCurrentUser.setText(a.toString());
        }
    }
    private void prilagodiFormu(){
        switch(tip){
            case CLAN:
                jmClan.setVisible(false);
                jmUsluga.setVisible(false);
                jmiOdgovoriNaZahteve.setVisible(false);
                
                break;
            case ADMINISTRATOR:
                jmiPodnesiZahtev.setVisible(false);
                jmiMojiZahtevi.setVisible(false);
                
                break;
                
        }
    }

    public void setTip(TipKorisnika tip) {
        this.tip = tip;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmClan;
    private javax.swing.JMenu jmUsluga;
    private javax.swing.JMenu jmZahtev;
    private javax.swing.JMenuItem jmiMojiZahtevi;
    private javax.swing.JMenuItem jmiNovaUsluga;
    private javax.swing.JMenuItem jmiNoviClan;
    private javax.swing.JMenuItem jmiOdgovoriNaZahteve;
    private javax.swing.JMenuItem jmiPodnesiZahtev;
    private javax.swing.JMenuItem jmiPretragaClanova;
    private javax.swing.JMenuItem jmiPretragaUsluga;
    private javax.swing.JLabel lblSat;
    private javax.swing.JTextField txtCurrentUser;
    // End of variables declaration//GEN-END:variables

    private void pokreniNitSat() {
        NitSat nit = new NitSat(lblSat);
        nit.start();
    }
}
