/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.zahtev;

import domen.Clan;
import domen.OpstiDomenskiObjekat;
import domen.StatusZahteva;
import domen.Usluga;
import domen.VrstaUsluge;
import domen.Zahtev;
import forme.FormMode;
import forme.usluga.FSelektovanjeUsluge;
import forme.usluga.FSelektovanjeVrstaUsluge;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import kontroler.Kontroler;
import modeli.ModelTabeleZahtev;
import transfer.ServerskiOdgovor;
import validacija.FormValidator;

/**
 *
 * @author USER
 */
public class FZahtev extends javax.swing.JDialog {

    /**
     * Creates new form FZahtev
     */
    public FZahtev(java.awt.Frame parent, boolean modal, FormMode rezim) {
        super(parent, modal);
        initComponents();
        podesiFormu();
        podesiTabelu();
        popuniKomboVrsta();
        podesiIndekseKomboa();       
        prilagodiFormu(rezim);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCurrentUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbVrstaUsluge = new javax.swing.JComboBox();
        cmbUsluga = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnPodnesiZahteve = new javax.swing.JButton();
        btnPonisti = new javax.swing.JButton();
        btnIzaberiVrstu = new javax.swing.JButton();
        btnIzaberiUslugu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDatumOdgovora = new javax.swing.JTextField();
        lblStatusZahteva = new javax.swing.JLabel();
        txtStatusZahteva = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblZahtev = new javax.swing.JTable();
        btnDodajZahtev = new javax.swing.JButton();
        btnObrisiZahtev = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Trenutni korisnik:");

        txtCurrentUser.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel4.setText("Vrsta usluge: ");

        cmbVrstaUsluge.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbVrstaUsluge.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVrstaUslugeItemStateChanged(evt);
            }
        });

        cmbUsluga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Usluga: ");

        btnPodnesiZahteve.setText("Podnesi zahteve");
        btnPodnesiZahteve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPodnesiZahteveActionPerformed(evt);
            }
        });

        btnPonisti.setText("Ponisti");
        btnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiActionPerformed(evt);
            }
        });

        btnIzaberiVrstu.setText("Izaberi vrstu");
        btnIzaberiVrstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiVrstuActionPerformed(evt);
            }
        });

        btnIzaberiUslugu.setText("Izaberi uslugu");
        btnIzaberiUslugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiUsluguActionPerformed(evt);
            }
        });

        jLabel3.setText("Datum odgovora: ");

        txtDatumOdgovora.setEnabled(false);

        lblStatusZahteva.setText("Status zahteva: ");

        txtStatusZahteva.setEnabled(false);

        tblZahtev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblZahtev);

        btnDodajZahtev.setText("Dodaj zahtev");
        btnDodajZahtev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajZahtevActionPerformed(evt);
            }
        });

        btnObrisiZahtev.setText("Obrisi zahtev");
        btnObrisiZahtev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiZahtevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(352, 352, 352)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnIzaberiUslugu, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(btnIzaberiVrstu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btnPonisti, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btnPodnesiZahteve, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(btnDodajZahtev, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnObrisiZahtev, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblStatusZahteva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                    .addGap(17, 17, 17)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtStatusZahteva, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbVrstaUsluge, 0, 199, Short.MAX_VALUE)
                                            .addComponent(cmbUsluga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDatumOdgovora))))))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbVrstaUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzaberiVrstu))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUsluga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnIzaberiUslugu))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatumOdgovora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStatusZahteva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatusZahteva))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajZahtev)
                    .addComponent(btnObrisiZahtev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPonisti)
                    .addComponent(btnPodnesiZahteve))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnPonistiActionPerformed

    private void cmbVrstaUslugeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVrstaUslugeItemStateChanged
        if (cmbVrstaUsluge.getSelectedItem() != null) {
            cmbUsluga.setEnabled(true);
            btnIzaberiUslugu.setEnabled(true);

            VrstaUsluge vu = (VrstaUsluge) cmbVrstaUsluge.getSelectedItem();
            Kontroler.getInstance().getMapa().put("izabrana_vrsta", vu); // dodao
            
            popuniKomboUsluga(vu);
            cmbUsluga.setSelectedIndex(-1);

        }
    }//GEN-LAST:event_cmbVrstaUslugeItemStateChanged

    private void btnPodnesiZahteveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPodnesiZahteveActionPerformed
        ModelTabeleZahtev mtz = (ModelTabeleZahtev) tblZahtev.getModel();
        if(mtz.getZahtevi().isEmpty()){
            JOptionPane.showMessageDialog(this, "Lista mora sadrzati bar 1 zahtev!");
            return;
        }
        List<Zahtev> listaZahteva = mtz.getZahtevi();
        
        ServerskiOdgovor so = Kontroler.getInstance().zapamtiZahteve(listaZahteva);
        JOptionPane.showMessageDialog(this, so.getPoruka());
    
        mtz.setZahtevi(new ArrayList<>());
    }//GEN-LAST:event_btnPodnesiZahteveActionPerformed

    private void btnIzaberiVrstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiVrstuActionPerformed
        new FSelektovanjeVrstaUsluge(null, true).setVisible(true);
        VrstaUsluge vu = (VrstaUsluge) Kontroler.getInstance().getMapa().get("izabrana_vrsta");
        cmbVrstaUsluge.setSelectedItem(vu);
    }//GEN-LAST:event_btnIzaberiVrstuActionPerformed

    private void btnIzaberiUsluguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiUsluguActionPerformed
        VrstaUsluge vu = (VrstaUsluge) cmbVrstaUsluge.getSelectedItem();
        Kontroler.getInstance().getMapa().put("izabrana_vrsta", vu);
        new FSelektovanjeUsluge(null, true).setVisible(true);
        Usluga u = (Usluga) Kontroler.getInstance().getMapa().get("izabrana_usluga");
        cmbUsluga.setSelectedItem(u);
    }//GEN-LAST:event_btnIzaberiUsluguActionPerformed

    private void btnDodajZahtevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajZahtevActionPerformed
        boolean validniComboBox = FormValidator.getInstance().validateComboSelection(cmbUsluga,cmbVrstaUsluge);
        if(!validniComboBox){
            JOptionPane.showMessageDialog(this, FormValidator.getInstance().getValidationMessage());
            return;
        }
        Usluga u = (Usluga) cmbUsluga.getSelectedItem();
        Clan c = (Clan) Kontroler.getInstance().getMapa().get("clan");
        StatusZahteva status = StatusZahteva.U_PRIPREMI;
        
        Zahtev z = new Zahtev(c, u, status);
        ModelTabeleZahtev mtz = (ModelTabeleZahtev) tblZahtev.getModel();
        mtz.dodajZahtev(z);
    }//GEN-LAST:event_btnDodajZahtevActionPerformed

    private void btnObrisiZahtevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiZahtevActionPerformed
        int row = tblZahtev.getSelectedRow();
        if(row != -1){
            ModelTabeleZahtev mtz = (ModelTabeleZahtev) tblZahtev.getModel();
            mtz.obrisiZahtev(row);
        }
    }//GEN-LAST:event_btnObrisiZahtevActionPerformed
    private void podesiIndekseKomboa() {
        cmbVrstaUsluge.setSelectedIndex(-1);
        cmbUsluga.setSelectedIndex(-1);

    }

    /**
     * @param args the command line arguments
     */
    private void podesiFormu() {
        setLocationRelativeTo(null);
        Clan c = (Clan) Kontroler.getInstance().getMapa().get("clan");
        txtCurrentUser.setText(c.toString());

        cmbUsluga.setEnabled(false);
        btnIzaberiUslugu.setEnabled(false);

    }

    private void popuniKomboVrsta() {
        List<VrstaUsluge> lista = Kontroler.getInstance().vratiVrsteUsluga();
        cmbVrstaUsluge.setModel(new DefaultComboBoxModel(lista.toArray()));
    }

    private void popuniKomboUsluga(VrstaUsluge vu) {
        Usluga u = new Usluga();
        u.setVrstaUsluge(vu);
        List<Usluga> lista = Kontroler.getInstance().vratiUsluge(u);
        cmbUsluga.setModel(new DefaultComboBoxModel(lista.toArray()));
    }

    private void prikazZahteva(Zahtev z) {
        cmbVrstaUsluge.setSelectedItem(z.getUsluga()== null || z.getUsluga().getVrstaUsluge() == null ? null : z.getUsluga().getVrstaUsluge());
        cmbUsluga.setSelectedItem(z.getUsluga() != null ? z.getUsluga() : null);
        
        txtStatusZahteva.setText(z.getStatusZahteva() == null ? null : z.getStatusZahteva().name());

        if (z.getDatumOdgovora() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            txtDatumOdgovora.setText(sdf.format(z.getDatumOdgovora()));
            //txtDatumOdgovora.setText(z.getDatumOdgovora().toString());
        }
    }

    private void postaviZahtev() {
        Zahtev z = (Zahtev) Kontroler.getInstance().getMapa().get("izabrani_zahtev");
        prikazZahteva(z);
    }
    private void prilagodiFormu(FormMode rezim){
        switch(rezim){
            case NEW:
                txtDatumOdgovora.setVisible(false);
                jLabel3.setVisible(false);
                lblStatusZahteva.setVisible(false);
                txtStatusZahteva.setVisible(false);
                cmbUsluga.setEnabled(false);
                cmbVrstaUsluge.setEnabled(true);
                btnIzaberiUslugu.setVisible(true);
                btnIzaberiUslugu.setEnabled(false);
                btnIzaberiVrstu.setVisible(true);
                btnPodnesiZahteve.setVisible(true);
                jScrollPane1.setVisible(true);
                break;
            case VIEW:
                txtDatumOdgovora.setVisible(true);
                jLabel3.setVisible(true);
                lblStatusZahteva.setVisible(true);
                txtStatusZahteva.setVisible(true);
                btnDodajZahtev.setVisible(false);
                btnObrisiZahtev.setVisible(false);
                
                
                cmbVrstaUsluge.setEnabled(false);
                jScrollPane1.setVisible(false);
                btnIzaberiUslugu.setVisible(false);
                btnIzaberiVrstu.setVisible(false);
                btnPodnesiZahteve.setVisible(false);
                postaviZahtev();
                cmbUsluga.setEnabled(false);
                this.pack();
                break;
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajZahtev;
    private javax.swing.JButton btnIzaberiUslugu;
    private javax.swing.JButton btnIzaberiVrstu;
    private javax.swing.JButton btnObrisiZahtev;
    private javax.swing.JButton btnPodnesiZahteve;
    private javax.swing.JButton btnPonisti;
    private javax.swing.JComboBox cmbUsluga;
    private javax.swing.JComboBox cmbVrstaUsluge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatusZahteva;
    private javax.swing.JTable tblZahtev;
    private javax.swing.JTextField txtCurrentUser;
    private javax.swing.JTextField txtDatumOdgovora;
    private javax.swing.JTextField txtStatusZahteva;
    // End of variables declaration//GEN-END:variables

    private void ocistiFormu() {
        prikazZahteva(new Zahtev());
    }

    private void podesiTabelu() {
        ModelTabeleZahtev mtz = new ModelTabeleZahtev();
        tblZahtev.setModel(mtz);
    }

    
}
